// Demo data for the application preview
export const demoDemoUser = {
  id: "demo-user-1",
  email: "demo@waiz.com",
  username: "demo_household",
  userType: "household" as const,
  profileComplete: true,
  phone: "+63-917-123-4567",
  address: "123 Session Road, Baguio City",
  name: "Demo Household User",
  avatar: null,
  createdAt: new Date(),
};

export const demoJunkshops = [
  {
    id: "junkshop-1",
    name: "Eco Recycle Hub",
    email: "info@ecorecycles.com",
    phone: "+63-917-555-0001",
    address: "456 Burnham Road, Baguio City",
    description: "Premium junkshop specializing in electronics and metals",
    avatar: null,
    coordinates: { lat: 16.4023, lng: 120.5960 },
    acceptedMaterials: ["Electronics", "Metals", "Plastics"],
    rating: 4.8,
    reviewCount: 147,
  },
  {
    id: "junkshop-2",
    name: "Green Waste Solutions",
    email: "contact@gws.com",
    phone: "+63-917-555-0002",
    address: "789 Easter Road, Baguio City",
    description: "Full-service recycling center for all material types",
    avatar: null,
    coordinates: { lat: 16.4089, lng: 120.6021 },
    acceptedMaterials: ["Paper", "Plastics", "Glass", "Metals"],
    rating: 4.6,
    reviewCount: 203,
  },
  {
    id: "junkshop-3",
    name: "Sustainable Materials Trading",
    email: "hello@smt.com",
    phone: "+63-917-555-0003",
    address: "321 Loakan Road, Baguio City",
    description: "Specializing in paper products and cardboard",
    avatar: null,
    coordinates: { lat: 16.3989, lng: 120.5901 },
    acceptedMaterials: ["Paper", "Cardboard"],
    rating: 4.9,
    reviewCount: 89,
  },
];

export const demoListings = [
  {
    id: "listing-1",
    title: "Electronics Bundle",
    description: "Old laptop, broken phone, and various cables",
    userId: "junkshop-1",
    userType: "junkshop" as const,
    material: "Electronics",
    quantity: 5,
    weight: 12,
    condition: "Used",
    price: 2500,
    images: [],
    status: "available",
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "listing-2",
    title: "Cardboard Boxes",
    description: "Clean cardboard boxes, perfect for storage or recycling",
    userId: "household-1",
    userType: "household" as const,
    material: "Cardboard",
    quantity: 20,
    weight: 8,
    condition: "Good",
    price: 150,
    images: [],
    status: "available",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "listing-3",
    title: "Metal Scraps",
    description: "Aluminum cans, copper wires, steel parts",
    userId: "household-2",
    userType: "household" as const,
    material: "Metals",
    quantity: 15,
    weight: 25,
    condition: "Used",
    price: 1800,
    images: [],
    status: "available",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
];

export const demoMessages = [
  {
    id: "msg-1",
    senderId: demoDemoUser.id,
    recipientId: "junkshop-1",
    content: "Hi! Are you still accepting electronics? I have an old laptop.",
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: true,
  },
  {
    id: "msg-2",
    senderId: "junkshop-1",
    recipientId: demoDemoUser.id,
    content: "Yes we are! We can offer 2000 pesos for working condition. Can you deliver?",
    timestamp: new Date(Date.now() - 1.5 * 60 * 60 * 1000),
    read: true,
  },
  {
    id: "msg-3",
    senderId: demoDemoUser.id,
    recipientId: "junkshop-2",
    content: "What's your best rate for cardboard boxes?",
    timestamp: new Date(Date.now() - 30 * 60 * 1000),
    read: false,
  },
];

export const demoTransactions = [
  {
    id: "txn-1",
    userId: demoDemoUser.id,
    listingId: "listing-1",
    junkshopId: "junkshop-1",
    amount: 2500,
    material: "Electronics",
    weight: 12,
    status: "completed",
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
  },
  {
    id: "txn-2",
    userId: demoDemoUser.id,
    listingId: "listing-2",
    junkshopId: "junkshop-3",
    amount: 150,
    material: "Cardboard",
    weight: 8,
    status: "completed",
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000),
  },
];

export const demoRates = [
  { material: "Paper", minRate: 1, maxRate: 3, unit: "pesos/kg" },
  { material: "Cardboard", minRate: 1.5, maxRate: 4, unit: "pesos/kg" },
  { material: "Plastics", minRate: 5, maxRate: 15, unit: "pesos/kg" },
  { material: "Metals", minRate: 50, maxRate: 200, unit: "pesos/kg" },
  { material: "Glass", minRate: 2, maxRate: 8, unit: "pesos/kg" },
  { material: "Electronics", minRate: 100, maxRate: 500, unit: "pesos/piece" },
];
